@host = http://localhost
@port = 5045

@Restaurants.API_HostAddress = https://localhost:7047

GET {{Restaurants.API_HostAddress}}/api/weatherforecast/23/example?max=5
Accept: application/json
ProjectUrl: {{$projectUrl}}
LocalDate: {{$datetime iso8601}} 
Random-int: {{$randomInt}}

###

POST {{Restaurants.API_HostAddress}}/api/weatherforecast
Content-Type: application/json

{
  "email": "test@test.com"
}

###

GET {{Restaurants.API_HostAddress}}/api/weatherforecast/currentDay

###

POST {{Restaurants.API_HostAddress}}/api/weatherforecast
Content-Type: application/json

"Chan"

###

@count=2
POST {{Restaurants.API_HostAddress}}/api/weatherforecast/generate?count={{count}}
Content-Type: application/json

{
  "min": 23,
  "max": 22
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

@Id=12
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{Id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Bonchon",
  "Description": "Chicken Joy",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "email@gmail.com",
  "ContactNumber": "777-777-66",
  "City": "Imus",
  "Street": "Salitran 1",
  "PostalCode": "41-114"
}

###

@Id=3
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{Id}}

###
